language: python
os: linux
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy"
install:
    - pip install '.[tests]'
script:
    py.test --flakes --cov=matchmock
after_success:
    coveralls
