language: python
sudo: false
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy"
install:
    - pip install -r test-requirements.txt
script:
    py.test --pep8 --flakes --cov=matchmock
after_success:
    coveralls
